server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://dpg-d29f28qli9vc73flbje0-a.singapore-postgres.render.com:5432/eum_postgres}
    username: ${DB_USER:eum_postgres_user}
    password: ${DB_PASSWORD:AIbnWHoSFF8x777Vr7KJozIdSyiEQRuK}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

springdoc:
  swagger-ui:
    path: /docs
