spring:
  config:
    import: optional:file:.env[.properties]


  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # H2 맞춤 SQL 생성
    hibernate:
      ddl-auto: create   # 테이블 새로 생성 (drop 에러 방지)
    show-sql: true

  mail:
    host: smtp.naver.com
    port: 465
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com

springdoc:
  swagger-ui:
    path: /docs
